### ISSUE TITLE
registrar dispensador y a obtener ethers

### ISSUE THREAD

**Issue by hvegax** [rmeb/dispensador-admin#12]

**Comment by hvegax** [comment]
![falla registro y obtener ethers.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b3cff78e8ae280011f8694c/125516c66e82c728ace21e0d46ee95962f83c3bb8aeeb650b04fffd4300628713d01ad2e62c5e63cb74769124d435cec03070511afbd9b21b4b36e70d9595ae4d6685671953b44acb8834de909e922894897aaaec81d9ebc6278bec1da0d2c14171980f55c30a3994cca5cf442e74e55a6017b.png)

**Comment by ocio28** [comment]
Corregido, el problema era que el servidor estaba sin ether, ahora chequea saldo y muestra un error descriptivo en la pagina, cargue mas ether al servidor.

**Comment by hvegax** [comment]
![captura de pantalla 2018-07-05 a la s 15 53 34](https://user-images.githubusercontent.com/9329016/42344868-a1854b4e-806b-11e8-99f9-773df8e4ebfc.png)

Hola, esto significa que está OK?

**Comment by ajunge** [comment]
Sip
