### ISSUE TITLE
agregar CD/CI

### ISSUE THREAD

**Issue by ajunge** [rmeb/dispensador-admin#8]
Seguir https://surge.sh/help/integrating-with-circleci

**Comment by ajunge** [comment]
Debe deployarse en: dispensador-admin.surge.sh

**Comment by ocio28** [comment]
Envié una petición de permisos al owner de "rmeb"

**Comment by ajunge** [comment]
Aprobado los persmisos para CircleCI

**Comment by ocio28** [comment]
Agregado a CircleCI
![captura de pantalla de 2018-07-06 14-05-34](https://user-images.githubusercontent.com/9950893/42393810-bda7355c-8125-11e8-87ac-107113fd9db0.png)
